### ISSUE TITLE
two guava jars causing homepage error

### ISSUE THREAD

**Issue by matthewhanson** [GeoNode/geoserver-geonode-ext#39]
There are two guava jars in the WEB-INF/lib directory that seem to be causing an error on the geoserver homepage, although geoserver seems to operate normally.  Removing the older guava jar fixes the problem.

**Comment by jj0hns0n** [comment]
@afabiani is this fixed? I havent tested recently.

**Comment by afabiani** [comment]
It should be fixed yes. 
At least it works fine on my side and the mvn dependency:tree shows to me just one guava JAR.

If someone else could double check would be good though.

Thanks,
-A.

**Comment by jj0hns0n** [comment]
I'm still seeing this with the geoserver.war downloaded from http://build.geonode.org/geoserver/latest ... I kicked off a new build to make sure it was latest.

**Comment by afabiani** [comment]
I just checked and the jar seems to be there. I'm going to do a fresh checkout and build the dependency tree again.

**Comment by afabiani** [comment]
It's ok now. It was not a code issue but a misconfiguration of the Jenkins task.

Adding "clean install" to the maven command solved the issue.

**Comment by jj0hns0n** [comment]
Confirmed
